### ISSUE TITLE
Shortcut for other filaments preheat.

### ISSUE THREAD

**Issue by Dan263737** [navaismo/Ender-3V3-SE#49]
Hi, i will like if you please add preheat shortcut for other filaments. There are now shortcuts for PLA and TPU - so it will be good if you add presets for PETG-240/90 and ABS-260/110. Thanks

**Comment by eduard-sukharev** [comment]
There's already preheat setups in Marlin and its number is configurable and their params can be adjusted in M-code and store in eeprom. Generating a list of presets from what saved i eeprom can be done.

**Comment by navaismo** [comment]
Added the corresponding menus in the latest [Release v1.0.9.7_9c](https://github.com/navaismo/Ender-3V3-SE/releases/tag/v1.0.9.7_9c). I got some issues with my printer and the EEPROM so please check if its saving values correctly and let me know if we can close the issue.

![Image](https://github.com/user-attachments/assets/40465aae-a5c1-4ba6-9eaa-33da9ab9db4c)

**Comment by Eitschman** [comment]
Hi. The new menus work well, but there is now a rendering problem. I think this happens because the original menus for PLA and TPU (and others) in the German language are two lines long...

![Image](https://github.com/user-attachments/assets/1fadfd68-cd03-4280-8ae5-b4b4c160d77e)

**Comment by Dan263737** [comment]
Thanks .works great

**Comment by navaismo** [comment]
> 
> Hi. The new menus work well, but there is now a rendering problem. I think this happens because the original menus for PLA and TPU (and others) in the German language are two lines long...
> 
> ![Image](https://github.com/user-attachments/assets/1fadfd68-cd03-4280-8ae5-b4b4c160d77e)

Oh, let me think in a way to erase the last row and then render again the option menú. That happens when scrolling up or down or both?

**Comment by Eitschman** [comment]
Both directions

**Comment by navaismo** [comment]
Should be Solved with the [Latest Release v1.0.9.7_9d](https://github.com/navaismo/Ender-3V3-SE/releases/tag/v1.0.9.7_9d)

**Comment by Eitschman** [comment]
The rendering issue is not solved, but i can live with that. Don't waste your time on this!

**Comment by navaismo** [comment]
I dont see anymore the ghosting on my menus could be the size of the rectangle that erase it, can you show me a screen  to see where is not cleaning it?

**Comment by Eitschman** [comment]
Here you can see it.

![Image](https://github.com/user-attachments/assets/925631ab-cbc6-43e4-ba37-2b44b2675e87)

**Comment by navaismo** [comment]
By any chance can you play with the size of the rectangles and compile it?
The function starts at https://github.com/navaismo/Ender-3V3-SE/blob/43a8b93eebbe43e7abd504b352a1fbfe92fc3b89/Marlin/src/lcd/dwin/e3v2/dwin.cpp#L7729

And you may need to play with the highlighted lines below, in my setup it does clean the ghosting:

```diff
  {
          if (HMI_flag.language < Language_Max)
          {
+           DWIN_Draw_Rectangle(1, Color_Bg_Black, 200, MBASE(0) - 8, 240, MBASE(0 + 2) - 12); // Clear previos line
            Draw_Menu_Line(0, ICON_SetEndTemp);
            DWIN_ICON_Show(HMI_flag.language, LANGUAGE_Hotend, 42, MBASE(0) + JPN_OFFSET);
            Show_Temp_Default_Data(0, 1);
            Show_Temp_Default_Data(1, 2);
            Show_Temp_Default_Data(2, 3);
          }
        }
        else if (index_temp == 7)
        {
          if (HMI_flag.language < Language_Max)
          {
+           DWIN_Draw_Rectangle(1, Color_Bg_Black, 200, MBASE(0) - 8, 240, MBASE(0 + 2) - 12); // Clear previos line
            Draw_Menu_Line(0, ICON_SetBedTemp);
            DWIN_ICON_Show(HMI_flag.language, LANGUAGE_Bedend, 42, MBASE(0) + JPN_OFFSET);
            Show_Temp_Default_Data(0, 2);
            Show_Temp_Default_Data(1, 3);
          }
        }
        else if (index_temp == 8)
        {
          if (HMI_flag.language < Language_Max)
          {
+          DWIN_Draw_Rectangle(1, Color_Bg_Black, 200, MBASE(0) - 8, 240, MBASE(0 + 2) - 12); // Clear previos line
            Draw_Menu_Line(0, ICON_FanSpeed);
            DWIN_ICON_Show(HMI_flag.language, LANGUAGE_Fan, 42, MBASE(0) + JPN_OFFSET);
            Show_Temp_Default_Data(0, 3);
          }
      ```

**Comment by Eitschman** [comment]
I will try it as soon as possible. This week is full of work, maybe in the evenings. I let you know.

**Comment by eduard-sukharev** [comment]
I had similar problems during development. It was some or other code error that made the firmware billable, but not bootable. Check that you don't have any edits in the code. Check that you're on the right git branch. Can't recommend anything specific, I had mine the same way due to my own faults in code (don't remember what it was)
